FROM node:24-alpine AS build

WORKDIR /app

COPY package*.json .

RUN npm ci --legacy-peer-deps

COPY . .

RUN npm run build

FROM node:24-alpine AS prod

WORKDIR /app

COPY --from=build /app/.output /app/.output

ENV NODE_ENV=production

EXPOSE 3000

CMD [ "node", ".output/server/index.mjs" ]
